package com.vidx.core.transcript

/** A caption track offered by the source. */
data class TranscriptTrack(
    val id: String,
    val langCode: String,
    val name: String,
    val autoGenerated: Boolean,
    /** Direct URL of the caption payload (json3 / vtt / srt / xml). */
    val fetchUrl: String,
)

data class TranscriptSegment(
    val startMs: Long,
    val endMs: Long,
    val text: String,
)

data class TranscriptResult(
    val track: TranscriptTrack,
    val segments: List<TranscriptSegment>,
    val source: String,           // "captions"
    val confidenceNote: String? = null,
) {
    val plainText: String get() = segments.joinToString(" ") { it.text.trim() }.trim()

    fun withTimestamps(): String = segments.joinToString("\n") {
        "${com.vidx.core.util.TimeFmt.transcriptStamp(it.startMs)}  ${it.text.trim()}"
    }

    fun withoutTimestamps(): String = plainText
}

/** Human-readable language names for the most common caption languages. */
object TranscriptLanguages {
    val common: Map<String, String> = mapOf(
        "en" to "English", "bn" to "বাংলা (Bengali)", "hi" to "हिन्दी (Hindi)",
        "ur" to "اردو (Urdu)", "ar" to "العربية (Arabic)", "es" to "Español (Spanish)",
        "fr" to "Français (French)", "de" to "Deutsch (German)", "pt" to "Português (Portuguese)",
        "ru" to "Русский (Russian)", "zh" to "中文 (Chinese)", "ja" to "日本語 (Japanese)",
        "ko" to "한국어 (Korean)", "it" to "Italiano (Italian)", "tr" to "Türkçe (Turkish)",
        "id" to "Bahasa Indonesia", "ms" to "Bahasa Melayu", "th" to "ไทย (Thai)",
        "vi" to "Tiếng Việt (Vietnamese)", "nl" to "Nederlands (Dutch)", "pl" to "Polski (Polish)",
        "uk" to "Українська (Ukrainian)", "fa" to "فارسی (Persian)", "he" to "עברית (Hebrew)",
        "ta" to "தமிழ் (Tamil)", "te" to "తెలుగు (Telugu)", "mr" to "मराठी (Marathi)",
        "gu" to "ગુજરાતી (Gujarati)", "pa" to "ਪੰਜਾਬੀ (Punjabi)", "ml" to "മലയാളം (Malayalam)",
        "kn" to "ಕನ್ನಡ (Kannada)", "sw" to "Kiswahili", "fil" to "Filipino",
    )

    fun label(langCode: String): String {
        val base = langCode.substringBefore('-').substringBefore('_').lowercase()
        val regional = langCode.replace('_', '-').lowercase()
        return common[regional] ?: common[base] ?: langCode.uppercase()
    }
}
